import React, { useState } from 'react';
import { Sparkles, RefreshCw, AlertCircle } from 'lucide-react';
import RoadmapVisualization from './components/RoadmapVisualization';
import { DEFAULT_ROADMAP } from './constants';
import { generateRoadmap } from './services/geminiService';
import { RoadmapData, LoadingState } from './types';

const App: React.FC = () => {
  const [data, setData] = useState<RoadmapData>(DEFAULT_ROADMAP);
  const [loadingState, setLoadingState] = useState<LoadingState>(LoadingState.IDLE);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const handleGenerate = async () => {
    if (loadingState === LoadingState.LOADING) return;
    
    setLoadingState(LoadingState.LOADING);
    setErrorMsg(null);
    
    try {
      const newData = await generateRoadmap();
      setData(newData);
      setLoadingState(LoadingState.SUCCESS);
    } catch (err) {
      console.error(err);
      setErrorMsg("Failed to generate new roadmap. Please check API Key configuration.");
      setLoadingState(LoadingState.ERROR);
    }
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-50 font-sans selection:bg-cyan-500/30">
      {/* Header / Hero */}
      <header className="relative pt-16 pb-8 px-4 text-center overflow-hidden">
        {/* Abstract Background Decoration */}
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-4xl h-96 bg-indigo-600/20 blur-[100px] rounded-full pointer-events-none" />
        
        <div className="relative z-10 flex flex-col items-center">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-slate-900/80 border border-slate-800 text-xs font-medium text-cyan-400 mb-6 backdrop-blur-sm">
            <Sparkles className="w-3 h-3" />
            <span>Powered by Gemini 2.5 Flash</span>
          </div>
          
          <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight mb-4">
            <span className="bg-clip-text text-transparent bg-gradient-to-r from-cyan-400 via-fuchsia-400 to-indigo-400 animate-gradient-x">
              Gemini Financial Vision
            </span>
            <br />
            <span className="text-slate-100">5-Year FinTech Roadmap</span>
          </h1>
          
          <p className="max-w-2xl mx-auto text-slate-400 text-lg md:text-xl leading-relaxed mb-8">
            Explore the projected evolution of Gemini AI in the Financial Sector. 
            From real-time banking intelligence to autonomous economic agents.
          </p>

          <button
            onClick={handleGenerate}
            disabled={loadingState === LoadingState.LOADING}
            className={`
              group relative flex items-center gap-2 px-6 py-3 rounded-full 
              font-semibold transition-all duration-300
              ${loadingState === LoadingState.LOADING 
                ? 'bg-slate-800 text-slate-500 cursor-not-allowed' 
                : 'bg-white text-slate-950 hover:bg-cyan-50 hover:shadow-[0_0_20px_rgba(34,211,238,0.5)]'
              }
            `}
          >
            {loadingState === LoadingState.LOADING ? (
              <RefreshCw className="w-5 h-5 animate-spin" />
            ) : (
              <Sparkles className="w-5 h-5 text-fuchsia-600 group-hover:text-fuchsia-500 transition-colors" />
            )}
            <span>
              {loadingState === LoadingState.LOADING ? 'Analyzing Trends...' : 'Regenerate Financial Future'}
            </span>
          </button>

          {errorMsg && (
            <div className="mt-4 flex items-center gap-2 text-red-400 bg-red-950/30 px-4 py-2 rounded-lg border border-red-900/50">
              <AlertCircle className="w-4 h-4" />
              <span className="text-sm">{errorMsg}</span>
            </div>
          )}
        </div>
      </header>

      {/* Main Content Area */}
      <main className="relative pb-24 px-4">
        {/* Render key to force re-animation on data change */}
        <RoadmapVisualization key={JSON.stringify(data)} data={data} />
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-900 bg-slate-950 py-8 text-center">
        <p className="text-slate-500 text-sm">
          &copy; {new Date().getFullYear()} Generated by Gemini 2.5 Flash & Engineered with React
        </p>
      </footer>
    </div>
  );
};

export default App;